### ISSUE TITLE
MatchGame Project - Restart does not show the Icons

### ISSUE THREAD

**Issue by giovanniz51** [head-first-csharp/fourth-edition#10]
If you play the game and you are finished selecting the Icons, if you click on restart game the Icons are not displayed again.

Solution:
In the SetUpGame Method you have to add:
`textBlock.Visibility = Visibility.Visible;`
before the ` if (textBlock.Name != "timeTextBlock")` statement.

Full SetUpGame Method:
`private void SetUpGame()
        {
            List<string> animalEmoji = new List<string>() 
            { 
                "😍","😍",
                "😪","😪",
                "🍔","🍔",
                "🍗","🍗",
                "🍙","🍙",
                "🚄","🚄",
                "🌍","🌍",
                "❤","❤",
            };

            Random random = new Random();

            foreach (TextBlock textBlock in mainGrid.Children.OfType<TextBlock>())
            {
                textBlock.Visibility = Visibility.Visible;

                if (textBlock.Name != "timeTextBlock")
                {
                    int index = random.Next(animalEmoji.Count);
                    string nextEmoji = animalEmoji[index];
                    textBlock.Text = nextEmoji;
                    animalEmoji.RemoveAt(index);
                }
            }

            timer.Start();
            tenthsOfSecondsElapsed = 0;
            matchesFound = 0;
        }`

![image](https://user-images.githubusercontent.com/7627884/102939462-a4835200-44ae-11eb-880c-6295fcbc7962.png)

**Comment by andrewstellman** [comment]
That's right! We have you add that code on page 45.
