### ISSUE TITLE
Wrong Value Instructions

### ISSUE THREAD

**Issue by meldwatts** [head-first-csharp/fourth-edition#11]
On the Card Picker Project, section 5 Set the Window Title and Size says:
    * Use the Layout section to set the width to 300.
And should have said 800.

**Comment by andrewstellman** [comment]
Thanks so much for letting us know! You're right, looks like I made a typo on that page. The second bullet in Step 5 in the CardPickerUI project should read:

> - Use the Layout section to set the height to **`300`** and the width to **`800`**.


We'll make sure this is fixed in the next printing.
