### ISSUE TITLE
.sln files don’t contain code

### ISSUE THREAD

**Issue by alanlw9** [head-first-csharp/fourth-edition#14]
There is little to no instruction on how to use this repository to follow along with the code in the book. None of the solutions work out of the box and I question why anyone would use this book and severely lacking repository. Zero stars.

**Comment by andrewstellman** [comment]
Thank you so much for letting me know about this! You're right, we definitely needed to add more detailed instructions to help our readers use the code in this repository. 

It's really important to me that we make this as easy to use as possible, so I just added a section called "How to use the code in this repository to follow along with the book" – here's the link: https://github.com/head-first-csharp/fourth-edition/blob/master/README.md#how-to-use-the-code-in-this-repository-to-follow-along-with-the-book
 
I added instructions for browsing the code, finding projects, an explanation of what the .sln file is, and how to download and run the code in Visual Studio and Unity. 

Please have a look—I hope this answers all of your questions. If you still have any questions about how to use the code in this repository, please let me know and I'll answer them as quickly as I can!

**Comment by andrewstellman** [comment]
Hi again,

I created a [video walkthrough that shows how to install Visual Studio, download the code, and use the .sln file to run the project in Visual Studio](https://github.com/head-first-csharp/fourth-edition#how-to-use-the-code-in-this-repository-to-follow-along-with-the-book). I made the video using a clean installation of Windows 10 to make sure it really works.

You can jump straight to the part where you download the code and load the game from Chapter 1: https://www.youtube.com/watch?v=73PGlIbkvV8&t=630s – that sections shows exactly how to use the .sln file to load the project in Visual Studio.

I hope this helps! I saw that someone posted a one-star review (you have no idea how much those can hurt us! 😢) mentioning the same issue that you did, so I really wanted to make sure to address this problem. Please let me know if there's anything else I can do to help.

Thanks,
Andrew

_Andrew Stellman
Author, Head First C#_

**Comment by alanlw9** [comment]
Author did a stellar job addressing what was more a lack of knowledge of my side than an issue. I appreciate the new resources and apologize for my misunderstanding.
