### ISSUE TITLE
Chapter 1 timer issue related to runtime tools

### ISSUE THREAD

**Issue by Daedalus359** [head-first-csharp/fourth-edition#17]
After I finished writing the matching game in chapter 1, my timer was not working properly. It would launch and count up (too slowly) for a second or so, then it would only advance by 0.1s every time I clicked an emoji. I used diff to compare my code with the files in this repo, and they were identical except for cosmetic differences (e.g. choice of emoji, empty lines).

I ended up watching the [video walkthrough of Ch1](https://youtu.be/aG08deKSwwI), and I noticed the mention of "runtime tools" around 15:30, so I disabled those. This immediately fixed my problem. I had missed / skipped the instructions to do this on p. 26, and there was nothing to indicate that these tools were anything more than a slight visual nuisance on my screen.

If this makes sense, I think the runtime tools issue should be mentioned on the [chapter 1 troubleshooting page](https://github.com/head-first-csharp/fourth-edition#did-you-run-into-trouble-with-the-project-in-the-first-chapter), since the connection between these runtime tools and the timer is not obvious to me.

**Comment by andrewstellman** [comment]
Thank you! I haven't seen this behavior before, so I really appreciate you reporting it. I've added it to the troubleshooting section: https://github.com/head-first-csharp/fourth-edition/blob/master/README.md#is-your-timer-going-slowly – we really appreciate the help!
