### ISSUE TITLE
where can i buy the Pdf ?

### ISSUE THREAD

**Issue by AustinHey** [head-first-csharp/fourth-edition#18]
Hello, it seems that the book is not available in Belgium.

Is it possible to buy the PDF version (not Kindle or Epub) ? Where can I find it ? 

I started the free chapters, looks great !

**Comment by andrewstellman** [comment]
Good question! Sorry it took so long to respond. We keep links to where you can buy versions of the book (including PDF) here: https://github.com/head-first-csharp/fourth-edition#how-to-get-head-first-c – but feel free to [DM me on Twitter](http://twitter.com/AndrewStellman/) and I'll see if I can help you out.
