### ISSUE TITLE
Updated Cover

### ISSUE THREAD

**Issue by spectrumcomputing** [head-first-csharp/fourth-edition#2]
Hi,

Really looking forward to this update.  Thank you.

Amazon seem to have an updated cover to the one you are displaying.  

https://www.amazon.co.uk/dp/1491976705/?coliid=I3VBP8O35MJE8M&colid=3KMIB2M3XM4D0&psc=1&ref_=lv_ov_lig_dp_it_im

Is the hope still for a summer release?

Best wishes

**Comment by andrewstellman** [comment]
Good eye! Yes, the amazing designers at O'Reilly came up with a new cover last design week. We're still tweaking it, but I think it looks fantastic. Obviously writing books isn't 100% predictable, but we're currently on track for a release later this year, sometime late fall. And I'll definitely post more early release material here as it becomes ready.
