### ISSUE TITLE
Chapter 9 Go Fish Unit Testing

### ISSUE THREAD

**Issue by brandonmcgarvey** [head-first-csharp/fourth-edition#21]
I am having a problem with unit test TestRandomValueFromHand() and I know it must be something wrong I have but my debugging is getting me nowhere and I am getting frustrated. The unit test is failing on the second assertion where random ValueToReturn = 16. It is coming back as "Five" instead of "Four". I added a debug line (code below) to write the card in the hand, referencing index h[16], and that is coming back "Four of Clubs" which seems good. So why is player.RandomValueFromHand().ToString() coming back as "Five"? I have gone as for as directly copying the code for RandomValueFromHand() from the Git repository. My Deck class is nearly identical as well. Any idea where I need to look closer? Thanks.

`public void TestRandomValueFromHand()
        {            
            var player = new Player("Owen", new Deck());
            
            var h = player.Hand.ToList();
            Debug.WriteLine($"{h[16]}");  //This returns "Four of Clubs"

            Player.Random = new MockRandom() { ValueToReturn = 0 };
            Assert.AreEqual("Ace", player.RandomValueFromHand().ToString());
            
            Player.Random = new MockRandom() { ValueToReturn = 16 };
            Debug.WriteLine(player.RandomValueFromHand().ToString());    // This returns "Five"
            Assert.AreEqual("Four", player.RandomValueFromHand().ToString());
            
            Player.Random = new MockRandom() { ValueToReturn = 51 };
            Assert.AreEqual("King", player.RandomValueFromHand().ToString());
            Debug.WriteLine(player.RandomValueFromHand().ToString());
        }`

**Comment by andrewstellman** [comment]
Sorry to hear that frustration! Believe me, we've all been there. Can you push your code to a Git repo? I'll have a look and see if I can spot the issue.

**Comment by brandonmcgarvey** [comment]
> Sorry to hear that frustration! Believe me, we've all been there. Can you push your code to a Git repo? I'll have a look and see if I can spot the issue.

Thanks, I appreciate it. https://github.com/brandonmcgarvey/GoFish
Note, GoFishConsole folder is the main proj and GoFish is the unit test proj.

**Comment by andrewstellman** [comment]
I'm so sorry! There's a copy-paste error in that PDF, and that's absolutely my fault. I feel really terrible putting you through that frustration! I've updated the PDF, and I'll go through the rest of the code in it and make sure there are no more errors. Super, super sorry about that!! 

Here's what that test method should look like: https://github.com/head-first-csharp/fourth-edition/blob/master/Code/Chapter_9/GoFish/GoFishTests/PlayerTests.cs#L111 – if you paste that method into your code, the test passes.

To answer your question, the reason player.Hand.ToList()[16] returns "Four of Clubs" but .player.RandomValueFromHand returns "Five" when you pass it a mock random object that returns 16 is that the RandomValueFromHand method sorts the list before choosing a random value. Before it's sorted the element at index 16 is Four of Clubs, after it's sorted the element is Five of Diamonds. 

Now, in this case the problem wasn't your fault at all! But if it helps, one way to troubleshoot problems like this in the future is to break up the chained methods and introduce _explaining variables_:

```
public Values RandomValueFromHand()
{
    var ordered = hand.OrderBy(card => card.Value);
    var selected = ordered.Select(card => card.Value);
    var r = Random.Next(hand.Count());
    var skipped = selected.Skip(r);
    var first = skipped.First();
    return first;
}  
```

Then you can place a breakpoint on the second line of the method, hover over `ordered`, click on Results View, and see the contents of the sequence.

**Comment by brandonmcgarvey** [comment]
No problem! Thank you for looking at it and thanks for the tip. I was looking closely at the logic of RandomValueFromHand, but was just thinking it through in my head. I still need to work on some of those bad habits lol. Breaking those methods up and analyzing each value is handy tip. Thanks again.

**Comment by andrewstellman** [comment]
I'm glad I could help! I hope the frustration is balanced by a little extra learning value.  Definitely let us know if you run into any other issues.
