### ISSUE TITLE
Can use namespaces (using System.Windows. Threading) some are greyed out, why cant i just use the namespace so i can move on, i followed the book, i even tried to type out the namespace and still no change.

### ISSUE THREAD

**Issue by teampofy** [head-first-csharp/fourth-edition#23]
![Capture](https://user-images.githubusercontent.com/58967438/140054231-21e539d0-8c5a-40f5-8f41-71bf88a3a31b.PNG)

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace MatchGame
{
    using System.Windows.Threading;
    public partial class MainWindow : Window
    {
        //Had the system to force to create a class for the dispatcher class
        DispatcherTimer timer = new DispatcherTimer();
        int tenthsOfSecondsElasped;
        int matchesFound;

        public MainWindow()
        {
            InitializeComponent();

            timer.Interval = TimeSpan.FromSeconds(.1);
            timer.Tick += Timer_Tick;
            SetupGame();
        }

        //Not sure why I had to manually create this method
        private void Timer_Tick(object sender, EventArgs e)
        {
            throw new NotImplementedException();
        }

        private void SetupGame()
        {
            List<String> animalEmoji = new List<String>()
            {
                "🚑","🚑",
                "🚓","🚓",
                "🚚","🚚",
                "🚌","🚌",
                "🛴","🛴",
                "🚅","🚅",
                "🚡","🚡",
                "🦽","🦽",
            };

            Random random = new Random();

            foreach (TextBlock textBlock in mainGrid.Children.OfType<TextBlock>())
            {
                int index = random.Next(animalEmoji.Count);
                string nextEmoji = animalEmoji[index];
                textBlock.Text = nextEmoji;
                animalEmoji.RemoveAt(index);
            }
        }

        //Created a variable to compare to the first object which is clicked
        TextBlock lastTextBlockClicked;
        //Create a flag to determine when we have a match which needs to be resetted when there is a match
        bool findingMatch = false;

        private void TextBlock_MouseDown(object sender, MouseButtonEventArgs e)
        {
            TextBlock textBlock = sender as TextBlock;
            /*
             finding match AKA are we on the first card or not 
             finding match = false, means that we are ready to select the first card
             finding match = true, means that we are ready to select the second card

            when findmatch is false
            we know that we dont have a selected card, 
            we know that this is the first card, so we hide, 
            so we set the flag to true to prepare to check if the next card will match
            to do this we assign the value of this card to the last card to compare against the new card
                        */
            if (findingMatch == false) 
                //which means that we dont have a match yet
            {
                textBlock.Visibility = Visibility.Hidden; //when the card is clicked we hide it via this property

                lastTextBlockClicked = textBlock; //

                findingMatch = true;
            }

            /*
             if the 1st card has been selected and hidden, when the compare the new card with the previous card
             if it matches the previous card then we hide this also
             and set the flag to false to prepare for the next pair of cards to try to match
             */
            else if (textBlock.Text == lastTextBlockClicked.Text)
            {
                textBlock.Visibility = Visibility.Hidden;

                findingMatch = false;
            }

            /*
             if the 2nd card doesnt match we simple dont touch the 2nd card
             instead we just make the first card visible again
             then we set the flag to false again to prepare for the 1st card again
             */

            else
            {
                lastTextBlockClicked.Visibility = Visibility.Visible;

                findingMatch = false;
            }
        }
    }

    internal class DispatcherTimer
    {
        public TimeSpan Interval { get; internal set; }
    }
}
`

**Comment by andrewstellman** [comment]
I'm sorry you're running into trouble! Can you publish your code to GitHub so I can download it and have a look?

**Comment by andrewstellman** [comment]
Hi! I see this code at the bottom of the code you pasted in, which doesn't match what's in the book:

```
internal class DispatcherTimer
{
    public TimeSpan Interval { get; internal set; }
}
```

Try deleting those lines from the file—when I do that, `using System.Windows.Threading;` gets un-grayed, and the red squiggly line under Tick disappears.

I hope this helps!

**Comment by andrewstellman** [comment]
Closing this issue, but please feel free to get back in touch if you run into any more problems!
