### ISSUE TITLE
Ch 6 Jewer Thief

### ISSUE THREAD

**Issue by Delgathar** [head-first-csharp/fourth-edition#30]
You might want to put in a warning about auto-generated classes or methods using the lightbulb.  The generated methods almost always have the private keyword added, and the classes have the internal keyword added. 

I typed the main and used the lightbulb to generate the classes for locksmith jewelThief, safe, etc, and the project would not build.  It gave a bunch of errors about Safe and owner being lower visibility than Jewel thief.  All my typed characters were correct, so it took me a while to realize that the word internal was added to my classes and messing things up.  Just tossing this in for food for thought.  Thank you.  

--
so the code for this exercise keeps changing from step to step in a way where it works, doesn't work, then works again.

also, the code for ReturnContents that says to add new also adds the word Jewels and replaces the protected keyword with public
``new public void ReturnContents(Jewels safeContents, Owner owner)
Originally both ReturnContents methods were protected too.  So Both Methods need to be changed to public or the program will not compile.  In the following note

```
// The JewelThief subclass hides a method in the Locksmith base class,
// so you can get different behavior from the same object based on the
// reference you use to call it!
// Declaring your JewelThief object as a Locksmith reference causes it to
// call the base class ReturnContents() method.
Locksmith calledAsLocksmith = new JewelThief();
calledAsLocksmith.ReturnContents(safeContents, owner);
// Declaring your JewelThief object as a JewelThief reference causes it to
// call JewelThief’s ReturnContents() method instead, because it hides
// the base class’s method of the same name.
JewelThief calledAsJewelThief = new JewelThief();
calledAsJewelThief.ReturnContents(safeContents, owner);

```
this doesn't work without making both ReturnContents public, then for the next step where they are made virtual and override, the protected status is returned.

Still progressing through the book.  I had gotten to the second lab in the 3rd edition before my computer died and I lost all my work.  Since every project builds on previous projects, re-using code and such, I didn't feel like starting over and set it aside.  Of course, I could have used the code but your code was different from mine and besides, 4th edition was supposed to come out real soon.  

Anyway, I'm really liking the new content and the methodology of teaching through the debugger even more than the previous edition.  A lot of this might be rehash, but a lot of content was added and I'm seeing it and liking it all.

**Comment by andrewstellman** [comment]
Thank you – that is an excellent idea! I'm just getting started on updating the book for the next edition of Visual Studio, I'll definitely add in a comment to help other readers avoid that situation.
