### ISSUE TITLE
Chapter 8 Unity Lab : foreach loop

### ISSUE THREAD

**Issue by Delgathar** [head-first-csharp/fourth-edition#38]
![image](https://user-images.githubusercontent.com/9401098/155347006-56103520-89c8-4d50-b5f5-09fc63ddc58e.png)

(my PDF viewer has this as page 931, not sure what the actual page number is but it is right before the Chapter 8 Unity Coding Challenge.  
![image](https://user-images.githubusercontent.com/9401098/155349698-6cb6a1a5-d8c5-4d15-904f-8d1ac569d7f7.png)

The code in the book gives the following error.  "GameObject does not contain a public instance or extension definition for GetEnumerator."  I thought maybe I forgot something so I went back and double-checked, but everything seemed to be as specified in the book. So far the unity lab has been "type this" and "do that".  So there aren't a lot of places for me to mess things up.  Then I opened up the HFCS Code folder and looked under chapter 8 Unity lab assets.  The GameController did not have the foreach loop under StartGame().  Since each chapter builds on the one before, I checked the chapter 9 unity lab too, but there was no foreach loop under StartGame() there either.  I looked for Destroy(ball) thinking maybe the code had moved to another method but there were no Destroy(ball) calls in the game controller script.

**Comment by andrewstellman** [comment]
You've got a typo. Your code is calling GameObject.FindGameObjectWithTag, which returns a GameObject reference. The code in the book is calling GameObject.FindGameObject**s**WithTag – note the extra s, it's finding GameObjects, not GameObject – which returns a collection of GameObject references.

**Comment by Delgathar** [comment]
> 
Wow.  I stared at that so hard because I didn't want to be told it was a typo, but it snuck in anyway.  Even after you said it was a typo I couldn't see it until you said to look for the s.

Thank you for you time.

**Comment by andrewstellman** [comment]
No worries, this just means you're a real developer now. I once spent over eight hours looking for a misplaced semicolon.
