### ISSUE TITLE
Chapter 9

### ISSUE THREAD

**Issue by Delgathar** [head-first-csharp/fourth-edition#40]
Hello,

Some minor issues in chapter 9 I was able to figure out for the most part but commenting on them here.  Also general commentary.

1.  descending keyword:  I like how this keyword was introduced after using the -variable the first two times.  I could never remember whether the minus would result in a descending or ascending list.  (does it put the next value before this value or this value before the other?) The keyword helps so much. 
2. This entire chapter feels like new content.  In 3rd edition, I made it as far as Serialization, but this all seems new.
3. Failed the magnets as usual, but it made me receptive to the following exercises.  I would not have figured out putting modifiers under the select clause.(sparrow-1) I also forgot that the whole LINQ query needed to be assigned to a reference so was left with a few extra "var animal ="
4. Anatomy of a Query - "Here's the updated LINQ query" > So the directions pretty much state that if the student updates the LINQ query as directed, the code will work.  It does not.  Foreach gives the error "Cannot convert type string error and, after substituting var for comic, "string does not contain a definition for Issue" errors happened.  I ended up making the following fix.
`			foreach (Comic comic in ComicDescriptions)
				Console.WriteLine($"{comic} is worth {Comic.Prices[comic.Issue]:c}");`
to
`			foreach(var comic in ComicDescriptions)
				Console.WriteLine(comic);`

An updated foreach or a note "Now you get an error, how should you fix it?" would be good here.  Being told updating the query would still work when it did not confused me a bit.  There was the redundancy of the old Console.WriteLine and the updated comic query returning the same string as a good hint though.

 5. "Add a unit test project" -> VS2019 does not have a MSTest core template for some reason.
 
![image](https://user-images.githubusercontent.com/9401098/156398319-f6677bb8-1e97-48bf-90b2-47deb04f4fc8.png)

While I still haven't figured out how to get the MSTest templates into VS2019, I did figure out if I opened the project in VS 2022 there is a MSTest project there.   I added it to the JimmyLinq solution but got a bunch of type or namespace errors.  It wasn't accepting the using.  In fact, when I tried typing it out. It only gave Microsoft.VisualBasic as an intellisence option.   I switched back ot 2019 but it still didn't accept the using.  Once I got near land I updated nuget and suddenly it worked. Reiterating the steps didn't reproduce the error so I suppose lack of internet stopped VS2022 from autoadding the dependencies.  Now that I've added UnitTest online, I can apparently add it offline too.  

I'd really like to find out how to get these missing templates added.  There will probably be a future exercise specifying another missing template soon.  While I've considered just practicing in 2022, I've been trying to stick to the same version as the book since Version issues caused me so many headaches in 2nd and 3rd edition.

6. Intentional bug 
![image](https://user-images.githubusercontent.com/9401098/156406519-704653f7-2df9-4a62-aee7-295f56f84577.png)

`			if (Comic.Prices[comic.Issue] < 100M)
				return PriceRange.Cheap;
			else
				return PriceRange.Expensive;
		}`

So the only thing I had done different before I saw that was mine was reversed ( > 100M return expensive) and I had added the M to the 100 literal (M for money, Thank you for that memnonic).  Removing the M and retyping if/else statements still gave the same results, so either this is a potential bug but not a problem in this instance, or I'm missing it.

Thank you.

**Comment by andrewstellman** [comment]
Thanks for taking the time to write all this! It's going to be really valuable when I get to updating chapter 9.
