### ISSUE TITLE
Mac-friendly version of MVVM bonus chapter?

### ISSUE THREAD

**Issue by jaytay579** [head-first-csharp/fourth-edition#50]
There appears to still be no Blazor WebAssembly or other compatibility solution for the MVVM bonus chapter. Is this still in development?

**Comment by andrewstellman** [comment]
Hi! Sorry I missed this comment a few months ago. We don't have a Mac version of the MVVM chapter, unfortunately. But I'm working on the 5th edition now, and we're moving all of the projects to .NET MAUI – which means the Mac and Windows versions will all be the same. I'll post all of the new material as free PDFs once it's done, so 4th edition readers can benefit from it without having to buy a new book.
