### ISSUE TITLE
Unanswered question on p. 324 (main book and Blazor PDF)

### ISSUE THREAD

**Issue by jaytay579** [head-first-csharp/fourth-edition#52]
In a callout box, there is a good question about **unassignedWorkers** occasionally not working right because the value is 0.9999999, but this is not answered anywhere, as far as I can see! _(Would be nice to know if the answer I'm giving my students is the same as what the authors intended...)_

**Comment by andrewstellman** [comment]
That's definitely a good question. It's like the 0.30000000000000004 problem in Chapter 4. A good way to handle this is to change unassignedWorkers from float to decimal. I'll have to give thought to updating this in the next edition of the book. Thanks!
