### ISSUE TITLE
MatchGame shows only ?

### ISSUE THREAD

**Issue by MRoest79** [head-first-csharp/fourth-edition#58]
Hi, i just started the book (first read it on holiday) and have to say i struggled a bit since the current version of Visual Studio uses different names for the modules to install and i'm actually still not sure if i need to run the triangle with start or without.

But i've created the code for MatchGame and double checked botth the C# and the XAML code but my pop up only shows the question marks.
I'm affraid i used the wrong type of project or something like that since my code seems ok. 

Any suggestions would be helpful. Thanks in advance,
Marc

**Comment by MRoest79** [comment]
Ok, that was to soon.
Apparently i hade 2 grids in my XAML...
```
    <Grid x:Name="mainGrid">
        <Grid>
        </Grid>
    </Grid>
```

Therefore it acted on the outer grid and not the inner grid

**Comment by andrewstellman** [comment]
I'm glad you solved your problem!
