### ISSUE TITLE
The Contest – win a free copy of Head First C#, submission form closed before supposed end date

### ISSUE THREAD

**Issue by fjsnogueira** [head-first-csharp/fourth-edition#9]
Hi,

I don't know if this is the right place, but, I was following this blog post: https://devblogs.microsoft.com/visualstudio/guest-post-learn-c-with-visual-studio-visual-studio-for-mac-and-unity-and-win-a-free-book/ to try to participate in a contest that should end by 11:59 p.m. PT,  December 9, 2020, and right now if I try to follow the link to the form (https://aka.ms/hfcs-book-challenge) I get into a page that says: "This giveaway is now completed. Watch the Visual Studio blog for winners to be announced!" and I believe that this might be wrong and that we are not yet after 11:59 p.m. PT,  December 9, 2020.

Regards,
Fernando Nogueira

**Comment by andrewstellman** [comment]
That's really weird! The contest is still running, so I just checked and I still see the form. 
I hope you were able to enter!

Here's a screenshot, just so you can see what I saw:

<img width="773" alt="Screen Shot 2020-12-09 at 11 34 59 PM" src="https://user-images.githubusercontent.com/7516297/101721955-2d45cb00-3a77-11eb-8618-065291cf7cf9.png">

**Comment by fjsnogueira** [comment]
<img width="640" alt="HeadFirstCSharp" src="https://user-images.githubusercontent.com/1634910/101756558-0c5c9480-3ace-11eb-9895-e1834d1e6853.PNG">
This is what I got yesterday at the time that I've opened the ticket

**Comment by fjsnogueira** [comment]
I don't know if the form is taking into account the timezone, but even in my timezone I was before 11:59pm.

**Comment by fjsnogueira** [comment]
I has rushing to finish the code before the end of the time as you can see on my repo: https://github.com/fjsnogueira/matchgame and after successfully finishing the challenge, I was unable to submit the form.

**Comment by andrewstellman** [comment]
No worries, I'll make sure you're entered into the contest and given an equal chance to win a copy of the book. I just need your email address. (If you don't want to post it publicly in an issue, you can send me a direct message on Twitter: [@AndrewStellman](https://twitter.com/AndrewStellman))
